### ISSUE TITLE
"Dev Builds" - Question about new installation instructions

### ISSUE THREAD

**Issue by whoisforte** [jamiewilson/predawn#108]
I've been running the same version of ST3 for the past 6 months, what is different about `predawn-DEV` that has to do with older versions of ST not supporting icons? Did something change? Is there a different version that is the "stable" release to use?

**Comment by jamiewilson** [comment]
Hey @whoisforte! Thanks for the question. Technically ST3 is still beta software, so I decided to call the file with the "new" features like sidebar icons, `predawn-DEV`. I you are using ST3, you should use the 'dev' version. eventually I will merge these, but since the 'stable' version of Sublime is still 2.x, I'll leave it for now. Let me know if you have any other questions!
