### ISSUE TITLE
Build 3103

### ISSUE THREAD

**Issue by AlennGK** [jamiewilson/predawn#124]
After upgrade...
"theme": "predawn-DEV.sublime-theme",
... not loading predawn theme :(

**Comment by Kinskitub** [comment]
same problem with me

upgrade to build 3103 today, and predawn fails
but, (i add) the others color schemes, those that come with sublime default, in my case,  do not work too well either. very slow to load, or just load in the current tab. (I had an open project, several files)

so..  I do not know if it is only a problem of predawn, or built 3103 or both.

sorry my english, regards.

**Comment by alexmccabe** [comment]
For some packages I had to remove and re-install them, give that a try.

**Comment by AlennGK** [comment]
I've done that, the whole new Sublime only with predawn.

**Comment by Kinskitub** [comment]
well, in my case I had to close the whole project and files

go to preferences-->package control --> upgrade/overwrite all packages.

reactivate predawn with ` "theme": "predawn-DEV.sublime-theme"`
in Preferences.sublime-settings and reopen the proyect

do not know why, but it worked closing the project, otherwise no
regards, sorry my bad english

**Comment by Kinskitub** [comment]
by the way, I love and I realized that i need predawn, spaceCadet, monokai and others my eyes hate you so deeply =)

**Comment by CurtisWist** [comment]
Thank you Kinskitub. That worked for me.

**Comment by AlennGK** [comment]
Not for me :(

**Comment by AlennGK** [comment]
Not for me :(
Edit: my bad! Overide was the thing.
