### ISSUE TITLE
Sidebar & Tabs Font Size

### ISSUE THREAD

**Issue by umarmughal** [jamiewilson/predawn#139]
I am on 27" screen everything seems fine but sidebar and tabs fonts are way too small, how can i change the size of these font, using Sublime Text 3 Build 3114, please advice.

**Comment by mattst** [comment]
You are in luck! I had the exact same problem, right down to the same monitor size.

There is some useful information [here](https://github.com/buymeasoda/soda-theme/wiki/Theme-customisation) about theme customization.

Basically, just like settings, you can override the values of a theme with a file named the same as the theme's file but stored in your `User` folder. In this case that is `predawn-DEV.sublime-theme`, although Sublime Text 2 users would use `predawn.sublime-theme`.

Since I've already done the modifications that you need, I've uploaded my file for you: [predawn-DEV.sublime-theme](https://gist.github.com/mattst/d9d442f339799f58e34a05937291cc0e)

You can download it in a zip or click on `raw` and save it directly. It must be placed in the following location of your Sublime Text config folder hierarchy.

    Packages/User/predawn-DEV.sublime-theme

If you edit my file you will be able to change the size of the following things:

- The tab bar height (overrides the various "predawn_tabs" size settings)
- The font size of tabs
- The font size of sidebar headings (i.e. GROUP NUM and FOLDERS labels)
- The font size of sidebar file names

Change each value a little at a time and the modifications will appear as soon as you save the file, allowing you to fine tune the values until you get them just right.

Hope this helps.

**Comment by UmarMughal** [comment]
Thanks man .. you saved my life, it works like a charm .. only issue i am having is tab font size, even i increase tab height still font cut down from bottom .. no idea why

**Comment by jamiewilson** [comment]
Thanks for help here! Glad you sorted it out. I'll take a look later to see if I can help with the issue with font cutting off. I think I might have discussed that in another Issue.

**Comment by mattst** [comment]
Glad to help.

@UmarMughal 

I think you should post a screen capture of it.

Did you try as big as `"tab_height": 50`?

**Comment by mmohamedsameer** [comment]
What is the font name? use in predawn official demo website?
